Update patch set 2
Patch Set 2:

> integration-distribution-verify-beryllium/432/ : FAILURE

2016-01-04 15:46:30,551 | ERROR | config-pusher    | ConfigRegistryImpl               | 103 - org.opendaylight.controller.config-manager - 0.4.0.SNAPSHOT | Configuration Transaction failed on 2PC, server is unhealthy
java.lang.IllegalStateException: Error - getInstance() failed for ModuleIdentifier{factoryName='sfc-l2renderer-impl', instanceName='sfc-l2renderer-impl'} in transaction TransactionIdentifier{name='ConfigTransaction-317-319'}

2016-01-04 15:46:30,529 | ERROR | config-pusher    | ConfigTransactionControllerImpl  | 103 - org.opendaylight.controller.config-manager - 0.4.0.SNAPSHOT | Commit failed on ModuleIdentifier{factoryName='sfc-l2renderer-impl', instanceName='sfc-l2renderer-impl'} in transaction TransactionIdentifier{name='ConfigTransaction-317-319'}
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Supplied QName (urn:cisco:params:xml:ns:yang:sfc-rsp?revision=2014-07-01)sfc-sl:vxlan-gpe is not a valid identity

That looks like a failure caused by SFC project. This needs to wait till that is examined and fixed.

Patch-set: 2
Reviewer: Gerrit User 2046 <2046@7fc14799-209e-464c-9743-7a06c2c21a81>
Label: Verified=0